apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: custom
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot","on-demand"]
   - key: "node.kubernetes.io/instance-type"
     operator: In
     values: [ "t3.micro","t3a.micro" ,"t2.medium" ]
  limits:
    resources:
      cpu: 1000
  provider:
    subnetSelector:
      karpenter.sh/discovery: karpenter
    securityGroupSelector:
      karpenter.sh/discovery: karpenter
    tags:
      karpenter.sh/discovery: karpenter
  ttlSecondsAfterEmpty: 30