apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot","on-demand"]
  limits:
    resources:
      cpu: 1000
  provider:
    subnetSelector:
      karpenter.sh/discovery: karpenter
    securityGroupSelector:
      karpenter.sh/discovery: karpenter
    tags:
      karpenter.sh/discovery: karpenter
  ttlSecondsAfterEmpty: 30